imports:
    - { resource: parameters.yml }
    - { resource: parametros.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    photo.producto: %kernel.root_dir%/../Resources/src/img/producto/
    photo.carrusel: %kernel.root_dir%/../Resources/src/img/carrusel/

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#Parametros para cambiar apariencia de la plataforma    
    globals:
        urlParam: '%app.urlParam%'
        pais: '%app.pais%'
        nombre: '%app.nombre%'
        tituloHome: '%app.tituloHome%'

        #serverMesages 
        serverOffline: '%app.serverOffline%'
        serverDuplicateName: '%app.serverDuplicateName%'
        serverDuplicateDepto: '%app.serverDuplicateDepto%'
        serverMsgSave: '%app.serverMsgSave%'
        serverMsgUpdate: '%app.serverMsgUpdate%'
        serverMsgCancel: '%app.serverMsgCancel%'
        serverCancel: '%app.serverCancel%'
        serverMsgDelete: '%app.serverMsgDelete%'
        serverError: '%app.serverError%'
    
    #loginMessages 
        usernameInvalidate: '%app.usernameInvalidate%'
        checkCaptcha: '%app.checkCaptcha%'
        invalidCaptcha: '%app.invalidCaptcha%'
        
    #Form Validations        
        #requiredFields 
        requiredFields: '%app.requiredFields%'        
        
        #cancelLabel 
        cancelLabel: '%app.cancelLabel%'
        
        #removeLabel 
        removeLabel: '%app.removeLabel%'
        
        #cancelButtonText 
        cancelButtonText: '%app.cancelButtonText%'
        
        #confirmButtonText 
        confirmButtonText: '%app.confirmButtonText%'
        
        #alternateconfirmButtonText 
        alternateconfirmButtonText: '%app.alternateconfirmButtonText%'
        
        #imageError 
        imageError: '%app.imageError%'
        
        #requiredFields 
        select2Label: '%app.select2Label%'
        
        # Opciones de usuario 
        editPass: '%app.editPass%'
        showLog: '%app.showLog%'
        settings: '%app.settings%'
        logOut: '%app.logOut%'
        
        #datatables 
        dtInfo: '%app.dtInfo%'
        dtInfoEmpty: '%app.dtInfoEmpty%'
        dtEmptyTable: '%app.dtEmptyTable%'
        dtNext: '%app.dtNext%'
        dtPrev: '%app.dtPrev%'
        dtProcessing: '%app.dtProcessing%'
        dtSearch: '%app.dtSearch%'
        dtLengthMenu: '%app.dtLengthMenu%'
        dtZeroRecords: '%app.dtZeroRecords%'
        
        #Botones 
        add: '%app.add%'
        delete: '%app.delete%'
        back: '%app.back%'
        show: '%app.show%'
        action: '%app.action%'
        save: '%app.save%'
        cancel: '%app.cancel%'
        
        #Tooltips 
        accountsTooltip: '%app.accountsTooltip%'
        saleStagesTooltip: '%app.saleStagesTooltip%'
        activitiesTooltip: '%app.activitiesTooltip%'
        calendarTooltip: '%app.calendarTooltip%'
        settingsTooltip: '%app.settingsTooltip%'
        reportsTooltip: '%app.reportsTooltip%'
        
        #icons 
        accountsIcon: '%app.accountsIcon%'
        saleStagesIcon: '%app.saleStagesIcon%'
        activitiesIcon: '%app.activitiesIcon%'
        calendarIcon: '%app.calendarIcon%'
        
        #Encabezados panel 
        pnHeadingLabelAdd: '%app.pnHeadingLabelAdd%'
        pnHeadingLabelEdit: '%app.pnHeadingLabelEdit%'
        
        #Login 
        tituloLogin: '%app.tituloLogin%'        
        usernameTxt: '%app.usernameTxt%'        
        passwordTxt: '%app.passwordTxt%' 

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
