security:
    encoders:
        Tienda\EcommerceBundle\Entity\CtlUsuario:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       10
        
    providers:      
        user_login:
            entity: { class: Tienda\EcommerceBundle\Entity\CtlUsuario, property: username }
        
    firewalls:
        #Firewalls para ingreso al Sistema de Tienda en Linea
        login_:
            pattern:  ^/$
            security: false
            context: primary_auth
            anonymous: ~
        secured_area_:
            pattern: ^/
            context: primary_auth
            switch_user: { role: ROLE_ADMIN, parameter: _change }
            form_login:
                login_path: /secured/login
                check_path: /secured/login_check
                default_target_path: /admin/dashboard
                #always_use_default_target_path: true 
                failure_path:      /secured/login
                #use_referer:         true
                success_handler: store.security.authentication_handler
                failure_handler: store.security.authentication_handler
            logout:
                path: /secured/logout
                target: /secured/login
            anonymous: ~                         
            
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/register/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/account/created, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role:  [ROLE_USER, ROLE_ADMIN]} 
        - { path: ^/secured/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #Roles admin
        - { path: ^/admin/*, role:  ROLE_ADMIN }        