# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    store.security.authentication_handler:
            class: Tienda\EcommerceBundle\Handler\AuthenticationHandler
            public: false
            arguments:
                - @service_container
                - @router
                - @session
                - @doctrine.orm.entity_manager    
